export const colors = {
    // mainBlack: `#262626`,
    // mainWhite: `#fff`,
    // mainGrey: `#aaa`,
    // primaryRGBA: `rgb(210, 170, 92, 0.3)`,
    // primaryColor: `#d2aa5c`,
    // primaryColorHover: `#ad7913`,
    // secondaryColor: `#F2AF29`,
    // thirdColor: `#474747`,
    // visitedColor: `red`,

    background: '#F0F0F0',
    darkPurple: '#0C002b',
    grey: '#f6f6f6',
    offWhite: '#FFFEFF',
    pink: '#FF718E',
    lightPink: '#ffb7c5',
    darkGrey: '#828d9d',
    lightGrey: '#dadde2',
    }
